version: '3.7'
services:

  cells:
    image: pydio/cells:latest
    volumes: 
      - data:/root/.config/pydio/cells/data
      - config:/root/.config
      - nfs:/home/data/nfs
    environment:
      - CELLS_BIND=files.${DOMAIN}:443
      - CELLS_EXTERNAL=https://files.${DOMAIN}
      - PYDIO_LOGS_LEVEL=production
      #- CELLS_NO_SSL=1
      - PUID=${PUID?Variable not set}
      - PGID=${PGID?Variable not set}
      - TZ=America/New_York
    networks:
      - traefik-public
      - private
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.frontend.rule=Host:files.${DOMAIN}
        - traefik.enable=true
        - traefik.port=443
        - traefik.protocol=https
        #- traefik.insecureSkipVerify=true
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
    command: [ '/bin/sh', '-c', 'echo `tail -2 /etc/hosts | head -1 | cut -f 1` > /home/ip.txt; sed -i "/PeerAddress/ s/: .*/: \"`cat /home/ip.txt`\",/g" /root/.config/pydio/cells/pydio.json; exec /bin/docker-entrypoint.sh cells start' ]

  mysql:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=cells
      - MYSQL_USER=pydio
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - private
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]

networks:
  traefik-public:
    external: true
  private:
    driver: overlay

volumes:
  data:
    driver: local
  config:
    driver: local
  db-data:
    driver: local
  nfs:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=${NFS_SERVER?error},rw
      o: addr=${NFS_SERVER?error}
      device: ":/volume1/nfs"
